In [8]:
# Check the versions of libraries

# Python version
import sys
print('Python: {}'.format(sys.version))
# scipy
import scipy
print('scipy: {}'.format(scipy.__version__))
# numpy
import numpy
print('numpy: {}'.format(numpy.__version__))
# matplotlib
import matplotlib
print('matplotlib: {}'.format(matplotlib.__version__))
# pandas
import pandas as pd
print('pandas: {}'.format(pd.__version__))
# scikit-learn
import sklearn
print('sklearn: {}'.format(sklearn.__version__))

Python: 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
scipy: 1.1.0
numpy: 1.14.3
matplotlib: 2.2.2
pandas: 0.23.0
sklearn: 0.19.1

In [2]:
# Load libraries
import pandas
from pandas.plotting import scatter_matrix
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [4]:
# Load dataset
df = pd.read_csv('ausdata.csv')
df = pd.DataFrame(df)
# shape
print(df.shape)
df.head(20)

(87648, 8)

      Date  Hour  DryBulb  DewPnt  WetBulb  Humidity  ElecPrice      SYSLoad
0   1/1/06   0.5    23.90   21.65    22.40      87.5      19.67   8013.27833
1   1/1/06   1.0    23.90   21.70    22.40      88.0      18.56   7726.89167
2   1/1/06   1.5    23.80   21.65    22.35      88.0      19.09   7372.85833
3   1/1/06   2.0    23.70   21.60    22.30      88.0      17.40   7071.83333
4   1/1/06   2.5    23.70   21.60    22.30      88.0      17.00   6865.44000
5   1/1/06   3.0    23.70   21.60    22.30      88.0      17.00   6685.92667
6   1/1/06   3.5    23.60   21.65    22.30      89.0      17.00   6548.62833
7   1/1/06   4.0    23.50   21.70    22.30      90.0      16.92   6487.83667
8   1/1/06   4.5    23.50   21.70    22.30      90.0      15.20   6449.17833
9   1/1/06   5.0    23.50   21.70    22.30      90.0      14.99   6388.27833
10  1/1/06   5.5    23.75   21.70    22.40      88.5      15.08   6395.48000
11  1/1/06   6.0    24.00   21.70    22.50      87.0      15.16   6494.33333
12  1/1/06   6.5    24.70   21.75    22.75      84.0      14.35   6715.20167
13  1/1/06   7.0    25.40   21.80    23.00      81.0      15.25   7062.48000
14  1/1/06   7.5    27.35   22.05    23.75      73.5      15.74   7532.11667
15  1/1/06   8.0    29.30   22.30    24.50      66.0      16.46   8037.86833
16  1/1/06   8.5    32.15   18.85    23.60      48.5      16.95   8623.73500
17  1/1/06   9.0    35.00   15.40    22.70      31.0      19.09   9169.36500
18  1/1/06   9.5    36.65   14.50    22.85      27.0      24.00   9600.79000
19  1/1/06  10.0    38.30   13.60    23.00      23.0      29.85  10005.30500

In [ ]:
df.describe()
df.groupby('Date').size()

In [ ]:
# histograms
df.hist()
plt.show()

In [ ]:
scatter_matrix(df)
plt.show()

In [23]:
data_x = df.drop(columns=['SYSLoad', 'Date'], axis=1)
data_y = df['SYSLoad']
scoring = 'accuracy'

In [25]:
from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    data_x, data_y, test_size=0.33, random_state=42)

In [33]:
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

regr = linear_model.LinearRegression()
regr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [35]:
y_train['SYSLoad'] = y_train['SYSLoad'].astype('int')
# Spot Check Algorithms
models = []
#models.append(('LR', LogisticRegression()))
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('CART', DecisionTreeClassifier()))
models.append(('NB', GaussianNB()))
models.append(('SVM', SVC()))
# evaluate each model in turn
results = []
names = []
for name, model in models:
	kfold = model_selection.KFold(n_splits=10, random_state=42)
	cv_results = model_selection.cross_val_score(model, X_train, y_train, cv=kfold, scoring=scoring)
	results.append(cv_results)
	names.append(name)
	msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
	print(msg)

KeyError: 'SYSLoad'